#!/usr/bin/env python3

"""
This enables use of radare2 for pwntools
Steps to enable
  1. Download and save as "pwntools-gdb" somewhere in your PATH
  2. chmod u+x pwntools-gdb
"""

import argparse
import re
import subprocess
import os

r2_python_template = """#!/usr/bin/env python

import os, r2pipe

r2 = r2pipe.open()
{user_commands:s}
"""

def pwntools_r2():
    parser = argparse.ArgumentParser()
    parser.add_argument("-x", nargs=1)
    parser.add_argument("-q", action="store_true")
    parser.add_argument("file", nargs=1)
    args = parser.parse_args()
    file_name = args.file[0]

    gdb_script = args.x[0]

    with open(gdb_script, "r") as f:
        gdb_script = f.read()
    ip, port = re.findall("target remote (.+):([0-9]+)", gdb_script)[0]

    user_commands = cmds  = "".join(["r2.cmd('" + s + "')\n" for s in gdb_script.split("\n") if s != ''][4:])
    script_file = args.x[0] + ".py"
    with open(script_file,"w") as f:
        f.write(r2_python_template.format(mod_name=os.path.basename(file_name), user_commands=user_commands))

    command = ["radare2","-d","-i",script_file, "gdb://{ip:s}:{port:s}".format(ip=ip, port=port)]
 #   command = ["screen","-t","pwntools-r2","r2","-d","-i",script_file, "gdb://{ip:s}:{port:s}".format(ip=ip, port=port)]

    subprocess.call(command)

def main():
    pwntools_r2()

if __name__ == '__main__':
    main()
